apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc
provisioner: hostpath.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer # 经过csi controller 决定调度到哪里, Immediate
allowVolumeExpansion: true
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.hostpath.csi/node
        values:
          - "koord-worker2"
